### ISSUE TITLE
How do you Open Source?

### ISSUE THREAD

**Issue by jdpedrie** [stephenplusplus/ama#17]
See title.

**Comment by stephenplusplus** [comment]
I copy what my mentors do and get lucky along the way.

Really just make time for it and do *something*. How to get started in OSS is not always obvious, and it's not always the same for everyone. I can't even say what a "tried and true" strategy is, because the path I found is likely different than what another's will be.

I can say for sure, though, don't go to GitHub.com and sit on the homepage going "Ummmmm, now what?" Just honestly do *anything* with the mindset of "How can I help?" Trivial PRs to fix typos and dead links are still great. It will at least get you in a contributing rhythm and you can meet people and become closer to code that way.

For me, getting code in my editor makes me feel much closer to a project than if I was just browsing on GitHub. When I'm in there, my "OMG CODE! I MISSED YOU I LOVE YOU!" instincts kick in, and I'll quickly find something I think ~~I can help with~~ **have to fix**.
