### ISSUE TITLE
What podcasts do you listen to and why?

### ISSUE THREAD

**Issue by robbbz** [stephenplusplus/ama#20]

**Comment by stephenplusplus** [comment]
I'm not a big podcast person, sadly. I work from home, so I mostly just listen to the noises of the house or my beloved Spotify playlists. I have a pretty nice strategy for my music collection I've been following since 2011, which is to group the songs I'm listening to per month. So, I can go back at any time and relive a "phase" of my life by just going to "March 2012" for example (when I found out I was having my first baby... awesome to remember the songs that I was listening to as my world was about to be rocked).

Sorry to go off the rails there. What podcasts do you listen to?

**Comment by robbbz** [comment]
None. That's why I asked you. @arthurvr and @passy said they listen a bunch of podcasts so I'm going to ask them too.
