### ISSUE TITLE
Who were/are your mentors?

### ISSUE THREAD

**Issue by arnellebalane** [stephenplusplus/ama#23]
And how did you get them to mentor you? :)

**Comment by stephenplusplus** [comment]
My answer is shockingly similar to https://github.com/passy/ama/issues/33, except with @passy added to my list of mentors. One of my best days was being welcomed to the TodoMVC team as well, and I remember having a chat with Passy on Hangouts (which I was already uncomfortable doing, feeling like I would be annoying), where I talked to him about how scary it was merging PRs and pushing to master and stuff. He was totally cool and said he related to that feeling as well.

Sindre intimidated the :hankey: out of me, but I just tried to play it cool, eventually learning I was just mistaking "being succinctly questioned why my idea is better" for "shortness." He has high standards and a lot on his plate, but he's always managed to help show me (directly and indirectly) the "way things should be."

And none of any of those stories could have happened without Addy. What can I even say? He's the Captain of GitHub as far as I'm concerned, a role model for more people than he could even realize. It's an honor just having a name he recognizes, let alone have him spend time drawing artwork for my daughter:

![2014-05-25](https://cloud.githubusercontent.com/assets/723048/8599994/7ab84c06-2631-11e5-93b4-62729a9502c3.jpg)

He's that kind of guy.

So many great things have happened since I started contributing to TodoMVC. Participating in OSS truly changed my life. I will continue to follow in the shadows of Addy, Sindre, and Passy, as they've led me to pure awesomeness so far.

**Comment by passy** [comment]
:')

:heart:

**Comment by sindresorhus** [comment]
<img align="left" width="183" alt="screen shot 2015-07-10 at 03 01 01" src="https://cloud.githubusercontent.com/assets/170270/8610236/ecd474da-26af-11e5-98ba-b240361cf8c5.png">


I still remember our first interaction, which was also your first pull request. I was thinking how awesome it was that you put so much work into this tiny detail: https://github.com/tastejs/todomvc/pull/342

**Comment by stephenplusplus** [comment]
:D I used to live for the :cake: and :sparkles: emoji my early PRs would get from you guys.

:heart:

**Comment by arnellebalane** [comment]
You guys are really cool, thanks :) Still waiting for @sindresorhus to answer [#120](https://github.com/sindresorhus/ama/issues/120) :p

**Comment by addyosmani** [comment]
:heart: :heartbeat: :revolving_hearts:
