### ISSUE TITLE
what's your favorite/most-effective learning method?

### ISSUE THREAD

**Issue by ahmadnassri** [stephenplusplus/ama#39]

**Comment by stephenplusplus** [comment]
Wow, I didn't realize I had questions waiting for me here on the AMA. Sorry about this delay :(

I'm not one to learn from experience, exactly. If I'm thrown into something, I generally feel too much pressure, throw away all my self-esteem, and basically check out until it's over. I didn't learn well in school, didn't go to college. I just spent a lot of time on the computer. I think I learn most by being alone and thinking.

In terms of JavaScript/coding, which is probably what you were actually interested in, I just stare at code until I figure out what it's doing. When I was first starting a new project at work, I stared at a repo of Java code (this language wasn't familiar to me at the time), and just drew mental lines between lines of code... Mental Stack Tracing™. That's really all it took. After that, it's just learning logistics (does it matter what I call the file / where I put it) and conventions.

In general, I try not to learn too much. I want to leave blank space so I can find my own path. If I just follow everyone else, then I'm just following everyone else.

I learned early on that I have a unique learning style, and that made me realize everyone probably has a unique learning style. I've just been stubborn enough about not caring if I got F's or didn't "get a good job". I simply could not "succeed" in high school, because I wasn't capable of it. I couldn't go to college, because I would be miserable. I *learned* myself first, and everything else has just been falling into place because of it.

This got so emo.

**Comment by sivaraam** [comment]
> If I just follow everyone else, then I'm just following everyone else.

[Dr. A. P. J. Abdul Kalam](https://en.wikipedia.org/wiki/A._P._J._Abdul_Kalam) says,
> "Every youth wants to be unique but the world is trying day and night to make him/her everybody else. Never stop fighting until you arrive at your destined place - that is, the unique you. Have an aim in life, continuously acquire knowledge, work hard, and have perseverance to realise the great life."
