### ISSUE TITLE
What's your favorite pony and why?

### ISSUE THREAD

**Issue by sindresorhus** [stephenplusplus/ama#5]

**Comment by stephenplusplus** [comment]
http://m.target.com/p/rockin-rider-brown-pony-rocker-animated-talks/-/A-10908129?ref=tgt_adv_XSG10001&AFID=google_pla_df&LNM=10908129&CPNG=Toys&kpid=10908129&LID=34pgs&ci_src=17588969&ci_sku=10908129&kpid=10908129&gclid=CLzjgOuIu8YCFQktaQodXGAFCQ because my daughter used to love playing on that thing.
